app:
    resource: "@AppBundle/Controller/"
    type:     annotation

points:
    type: rest
    resource: AppBundle\Controller\PointsController

statistics:
    type: rest
    resource: AppBundle\Controller\StatisticsController